---
apiVersion: v1
kind: Pod
metadata:
  name: database
spec:
  containers:
    - name: postgres
      image: docker.io/postgres
      ports:
        - containerPort: 5432
          hostPort: 5432
          hostIP: 127.0.0.1
          protocol: TCP
      env:
        - name: POSTGRES_DB
          value: "fracker"
        - name: POSTGRES_USER
          value: "fracker"
        - name: POSTGRES_PASSWORD
          value: "fracker"
      resources:
        limits:
          memory: "256Mi"
          cpu: 1.0
      restartPolicy: Never
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-volume
  volumes:
    - name: db-volume
      hostPath:
        path: /run/media/runage/code/@kamidere/fracker/database
        type: Directory
